# Generated by Django 5.2.10 on 2026-01-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prova',
            table='prova',
        ),
        migrations.AlterModelTable(
            name='questao',
            table='questao',
        ),
    ]
