# Generated by Django 5.2.10 on 2026-01-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_prova_table_alter_questao_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('prova_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prova')),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='materia_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.materia'),
            preserve_default=False,
        ),
    ]
