# Generated by Django 5.2.10 on 2026-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_materia_questao_materia_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='resposta_correta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='resposta_inserida',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
    ]
