# Generated by Django 5.2.10 on 2026-08-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questao_resposta_correta_questao_resposta_inserida'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='link_gabarito',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prova',
            name='link_prova',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
