# Generated by Django 5.2.10 on 2026-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prova_link_gabarito_prova_link_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questao',
            name='peso',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prova',
            name='link_gabarito',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='prova',
            name='link_prova',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
