# Generated by Django 5.2.10 on 2026-09-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_questao_anulada_questao_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='ordem',
            field=models.IntegerField(null=True),
        ),
    ]
