# Generated by Django 5.2.10 on 2026-09-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_materia_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='peso',
            field=models.FloatField(default=1),
        ),
    ]
